apiVersion: v1
kind: Service
metadata:
  name: {{ include "Collect1.fullname" . }}
  labels:
    {{- include "Collect1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort : {{ .Values.service.port }}
      protocol: TCP
      name: kafka-module
    - port: {{ .Values.service.subport }}
      targetPort : {{ .Values.service.subport }}
      protocol: TCP
      name: test-service
  selector:
    {{- include "Collect1.selectorLabels" . | nindent 4 }}
