apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "collect-alpha.fullname" . }}
  labels:
    {{- include "collect-alpha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName : {{ include "collect-alpha.fullname" . }}-api
  selector:
    matchLabels:
      {{- include "collect-alpha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "collect-alpha.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api-module
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          command: ["/bin/bash"]
          args:
          - "python3"
          - "/modules/app.py"
          - "{{ .Release.Name }}-kafka"
          - "{{ .Release.Name }}-hbase-master"
          - ">script.out 2>script.err &"
          - "&&"
          - "-ec"
          - "while :; do echo '.'; sleep 5 ; done ;"