apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "python.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: kafka-module
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: 
          - "/bin/sh"
          - "-ec"
          - "while :; do echo '.'; sleep 5 ; done"
          - "mkdir modules"
          - "cd modules"
          - "pip kafka-python"
          - "pip happybase"
          - "pip json"
          - "wget {{.Values.module.url}}"
          - "python3 app.py '{{ .Release.Name }}-kafka' '{{ .Release.Name }}-hbase-master' >> res.txt"
